### ISSUE TITLE
Inverted colors when using plt.imshow()

### ISSUE THREAD

**Issue by gabrielkunz** [GabrielKunz/seam-carving#3]
When using the new added function plotResult(), the plt.imshow() call for the original image and the output are displayed with inverted colors. I've tried to plot them using the .astype(np.uint8) attribute, but without success.
![Screen Shot 2020-09-26 at 11 22 25 PM](https://user-images.githubusercontent.com/23388401/94354198-2b12c980-004f-11eb-8949-b1a4972acb5c.png)

**Comment by Schukuratsu** [comment]
Talvez algo a ver com a ordenação das camadas rgb, no opencv a ordem é bgr, então se tu usar o opencv pra abrir e usar outra coisa pra plotar vai acontecer isso

**Comment by LincolnVS** [comment]
> Talvez algo a ver com a ordenação das camadas rgb, no opencv a ordem é bgr, então se tu usar o opencv pra abrir e usar outra coisa pra plotar vai acontecer isso

You are right @Schukuratsu.

@GabrielKunz you need to swap the color order:

```
img1 = cv2.imread("tiger.jpg", 3)

b,g,r = cv2.split(img1)           # get b, g, r
rgb_img1 = cv2.merge([r,g,b])     # switch it to r, g, b

plt.subplot(121),plt.imshow(img1),plt.title('BGR')
plt.subplot(122),plt.imshow(rgb_img1 ),plt.title('RGB')
```

Code from: [Paul Terwilliger](https://stackoverflow.com/a/39904259)

**Comment by LincolnVS** [comment]
Another way to change the color order is:

```
img = cv2.imread("tiger.jpg")
img= cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
````

**Comment by gabrielkunz** [comment]
@Schukuratsu thanks for the help & @LincolnVS thanks for the fix! Closing this issue.
