### ISSUE TITLE
'AttributeError' when trying to use Canny edge detector for energy mapping

### ISSUE THREAD

**Issue by gabrielkunz** [GabrielKunz/seam-carving#5]
I'm trying to implement the Canny edge detector in the [BackwardEnergy](https://github.com/GabrielKunz/seam-carving/blob/master/src/backward_energy.py) class for energy mapping by adapting the code from [https://github.com/FienSoP/canny_edge_detector](https://github.com/FienSoP/canny_edge_detector).

I've made some adjustments to call the edge detector by using the 'be.canny(img)' statement in the main program [sc.py](https://github.com/GabrielKunz/seam-carving/blob/master/src/sc.py) but I'm getting an 'AttributeError' when trying to run the program:

```console
foo@bar ~ % python3 sc.py -in image.jpg -scale 0.5 -seam h -energy c
  0%|                                                     | 0/320 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "sc.py", line 236, in <module>
    img = resize(img, SCALE)
  File "sc.py", line 40, in resize
    img = seamCarving(img)
  File "sc.py", line 127, in calculateEnergy
    energy_map = be.canny(img)
  File "~/src/backward_energy.py", line 154, in canny
    self.energy_map = self.canny_edge_detector.detect(img, sigma=1.4, kernel_size=5, lowthreshold=0.09, highthreshold=0.17, weak_pixel=100)
AttributeError: 'CannyEdgeDetector' object has no attribute 'detect'
```

**Comment by LincolnVS** [comment]
It is an indentation error!

From line [181](https://github.com/GabrielKunz/seam-carving/blob/851f6dbe5bdcf3f4ffbfee822444103a0f23a29f/src/backward_energy.py#L181) to line [291](https://github.com/GabrielKunz/seam-carving/blob/851f6dbe5bdcf3f4ffbfee822444103a0f23a29f/src/backward_energy.py#L294), you have to remove a tab.

**Comment by gabrielkunz** [comment]
Thanks for the help @LincolnVS ! Closing the issue.
